# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/ui_window.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(949, 891)
        self.graphicsView_2 = QtWidgets.QGraphicsView(Form)
        self.graphicsView_2.setGeometry(QtCore.QRect(610, 130, 320, 320))
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(240, 100, 67, 17))
        self.label_4.setObjectName("label_4")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 10, 229, 31))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.comboBox = QtWidgets.QComboBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout.addWidget(self.comboBox)
        self.layoutWidget1 = QtWidgets.QWidget(Form)
        self.layoutWidget1.setGeometry(QtCore.QRect(260, 10, 151, 31))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.spinBox = QtWidgets.QSpinBox(self.layoutWidget1)
        self.spinBox.setMinimum(3)
        self.spinBox.setMaximum(40)
        self.spinBox.setSingleStep(2)
        self.spinBox.setProperty("value", 15)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout_2.addWidget(self.spinBox)
        self.stackedWidget = QtWidgets.QStackedWidget(Form)
        self.stackedWidget.setGeometry(QtCore.QRect(240, 130, 320, 320))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.stackedWidget.addWidget(self.page_4)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(20, 230, 111, 71))
        self.groupBox.setObjectName("groupBox")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton.setGeometry(QtCore.QRect(10, 20, 91, 20))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_2.setGeometry(QtCore.QRect(10, 50, 91, 20))
        self.radioButton_2.setObjectName("radioButton_2")
        self.pushButton_6 = QtWidgets.QPushButton(Form)
        self.pushButton_6.setGeometry(QtCore.QRect(610, 100, 131, 25))
        self.pushButton_6.setObjectName("pushButton_6")
        self.formLayoutWidget = QtWidgets.QWidget(Form)
        self.formLayoutWidget.setGeometry(QtCore.QRect(810, 100, 121, 21))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_6.setText("")
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_6)
        self.splitter = QtWidgets.QSplitter(Form)
        self.splitter.setGeometry(QtCore.QRect(790, 100, 134, 17))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(20, 480, 67, 17))
        self.label_7.setObjectName("label_7")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 40, 418, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_3.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_3.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_3.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_3.addWidget(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_3.addWidget(self.pushButton_5)
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 520, 911, 361))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.sample_1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.sample_1.setText("")
        self.sample_1.setObjectName("sample_1")
        self.gridLayout.addWidget(self.sample_1, 1, 1, 1, 1)
        self.sample_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.sample_2.setText("")
        self.sample_2.setObjectName("sample_2")
        self.gridLayout.addWidget(self.sample_2, 1, 2, 1, 1)
        self.sample_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.sample_8.setText("")
        self.sample_8.setObjectName("sample_8")
        self.gridLayout.addWidget(self.sample_8, 2, 3, 1, 1)
        self.sample_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.sample_3.setText("")
        self.sample_3.setObjectName("sample_3")
        self.gridLayout.addWidget(self.sample_3, 1, 3, 1, 1)
        self.sample_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.sample_4.setText("")
        self.sample_4.setObjectName("sample_4")
        self.gridLayout.addWidget(self.sample_4, 1, 4, 1, 1)
        self.sample_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.sample_9.setText("")
        self.sample_9.setObjectName("sample_9")
        self.gridLayout.addWidget(self.sample_9, 2, 4, 1, 1)
        self.sample_0 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.sample_0.setText("")
        self.sample_0.setObjectName("sample_0")
        self.gridLayout.addWidget(self.sample_0, 1, 0, 1, 1)
        self.sample_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.sample_7.setText("")
        self.sample_7.setObjectName("sample_7")
        self.gridLayout.addWidget(self.sample_7, 2, 2, 1, 1)
        self.sample_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.sample_6.setText("")
        self.sample_6.setObjectName("sample_6")
        self.gridLayout.addWidget(self.sample_6, 2, 1, 1, 1)
        self.sample_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.sample_5.setText("")
        self.sample_5.setObjectName("sample_5")
        self.gridLayout.addWidget(self.sample_5, 2, 0, 1, 1)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_4.setText(_translate("Form", "Input:"))
        self.label_3.setText(_translate("Form", "Model:"))
        self.comboBox.setItemText(0, _translate("Form", "None"))
        self.comboBox.setItemText(1, _translate("Form", "cape_1"))
        self.comboBox.setItemText(2, _translate("Form", "CelebA-HQ-center"))
        self.comboBox.setItemText(3, _translate("Form", "Paris-center"))
        self.comboBox.setItemText(4, _translate("Form", "ImageNet-center"))
        self.comboBox.setItemText(5, _translate("Form", "Places2-center"))
        self.comboBox.setItemText(6, _translate("Form", "CelebA-HQ-random"))
        self.comboBox.setItemText(7, _translate("Form", "Paris-random"))
        self.comboBox.setItemText(8, _translate("Form", "ImageNet-random"))
        self.comboBox.setItemText(9, _translate("Form", "Places2-random"))
        self.label_2.setText(_translate("Form", "Bush Width:"))
        self.groupBox.setTitle(_translate("Form", "Drawing mode:"))
        self.radioButton.setText(_translate("Form", "free-form"))
        self.radioButton_2.setText(_translate("Form", "rectangle"))
        self.pushButton_6.setText(_translate("Form", "Original/Output"))
        self.label_5.setText(_translate("Form", "<html><head/><body><p>Score:</p></body></html>"))
        self.label_7.setText(_translate("Form", "Samples:"))
        self.pushButton.setText(_translate("Form", "load"))
        self.pushButton_2.setText(_translate("Form", "random"))
        self.pushButton_3.setText(_translate("Form", "fill"))
        self.pushButton_4.setText(_translate("Form", "display mesh"))
        self.pushButton_5.setText(_translate("Form", "draw/clear"))
